### Obtener todos los pedido
GET http://localhost:3000/api/shipping

### Crear un nuevo pedido

# @name createGin
POST http://localhost:3000/api/shipping
Content-Type: application/json

{
    "address": "123 Main St",
    "city": "New York",
    "zipCode": "10001",
    "cardNumber": "1234567812345678",
    "expiryDate": "12/25",
    "cvv": "123",
    "cardholderName": "Jane Smith",
    "order": {
        "confirmDate": "2024-11-25T08:00:00Z",
        "user": {
            "name": "Mariana",
            "surname": "Lopez",
            "userName": "MariLop",
            "password": "mari1234",
            "type": "User",
            "mail": "mariana.lopez@hotmail.com",
            "cellphone": "3412768934",
            "age": 30,
            "birthDate": "1993-01-10",
            "dni": "41234567"
        },
        "linesOrder": [
            {
                "product": {
                    "code": "P9876",
                    "name": "Product E",
                    "priceUni": 10000,
                    "stock": 3
                },
                "quantity": 2
            }
        ],
        "totalAmount": 20000,
        "statusHistory": ["Order created", "Order processing"]
    }
}

### ID
@id = {{createGin.response.body.data.id}}

### Obtener uno en particular
GET http://localhost:3000/api/shippings/{{id}}

### Crear un nuevo shippingo
POST http://localhost:3000/api/shippings
Content-Type: application/json
{
    "address": "456 Elm St",
    "city": "Los Angeles",
    "zipCode": "90001",
    "cardNumber": "9876543298765432",
    "expiryDate": "11/24",
    "cvv": "456",
    "cardholderName": "John Doe",
    "order": {
        "confirmDate": "2024-11-12T09:30:00Z",
        "user": {
            "name": "Ricardo",
            "surname": "Fernandez",
            "userName": "RickyF",
            "password": "rickysecure",
            "type": "Admin",
            "mail": "ricardo.fernandez@gmail.com",
            "cellphone": "3312456789",
            "age": 40,
            "birthDate": "1984-11-20",
            "dni": "37456983"
        },
        "linesOrder": [
            {
                "product": {
                    "code": "P1234",
                    "name": "Product A",
                    "priceUni": 5000,
                    "stock": 10
                },
                "quantity": 2
            },
            {
                "product": {
                    "code": "P6789",
                    "name": "Product B",
                    "priceUni": 15000,
                    "stock": 4
                },
                "quantity": 1
            }
        ],
        "totalAmount": 25000,
        "statusHistory": ["Order created", "Payment received"]
    }
}

### Modificar un nuevo shippingo (PUT - recuro completo e idempotente)
PUT http://localhost:3000/api/shippings/{{id}}
Content-Type: application/json
{
    "address": "789 Oak St",
    "city": "New York",
    "zipCode": "10002",
    "cardNumber": "1234567812345678",
    "expiryDate": "12/25",
    "cvv": "123",
    "cardholderName": "Jane Smith",
    "order": {
        "confirmDate": "2024-12-05T15:45:00Z",
        "user": {
            "name": "Ana",
            "surname": "Gutierrez",
            "userName": "AnaGuti",
            "password": "gutierrezAna",
            "type": "User",
            "mail": "ana.gutierrez@yahoo.com",
            "cellphone": "3489756123",
            "age": 27,
            "birthDate": "1996-05-15",
            "dni": "42567890"
        },
        "linesOrder": [
            {
                "product": {
                    "code": "P2345",
                    "name": "Product D",
                    "priceUni": 3000,
                    "stock": 15
                },
                "quantity": 5
            }
        ],
        "totalAmount": 15000,
        "statusHistory": ["Order created", "Order shipped"]
        }
}


### Modificar un nuevo shippingo (PATCH - recurso parcial)
PATCH http://localhost:3000/api/shippings/{{id}}
Content-Type: application/json
{
    "address": "789 Maple St",
    "city": "Los Angeles",
    "zipCode": "90002"
}

### Borrar un elemento
DELETE http://localhost:3000/api/shippings/{{id}}